apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  initializers:
  annotations:
    "initializer.kubernetes.io/oga": |
      slack:
        channel: "#testoga"
        approvers:
          - "@bjhaid"
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      run: nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
